routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['install']], function () {

	Route::get('/', function () {
		return redirect('/dashboard');
	});

	Auth::routes();

	Route::group(['middleware' => ['auth']], function () {

		Route::any('/dashboard', 'DashboardController@index');

		Route::get('profile/show', 'ProfileController@profile_show');
		Route::get('profile/edit', 'ProfileController@profile_edit');
		Route::post('profile/update', 'ProfileController@profile_update');
		Route::get('password/change', 'ProfileController@password_change');
		Route::any('password/update', 'ProfileController@password_update');

		//only for Admin
		Route::group(['middleware' => ['permission:Admin,Librarian']], function () {
			Route::resource('users','UserController');

			Route::any('/general_settings', 'SettingsController@general_settings');

			Route::any('/notification_settings', 'SettingsController@notification_settings');

			Route::any('/backup_database', 'BackupController@backup_database');
		});

		//only for Admin,Librarian
		Route::group(['middleware' => ['permission:Admin,Librarian']], function () {
			Route::get('library/{page?}', 'LibraryController@index');

			Route::group(['prefix' => 'library'], function () {
				Route::resource('book_categories','BookCategoryController');

				Route::resource('books','BookController');

				Route::get('members/library_card/{id}', 'MemberController@library_card')->name('members.library_card');
				Route::resource('members','MemberController');

				Route::get('circulations/book_return_info/{id}', 'CirculationController@book_return_info');
				Route::post('circulations/book_return/{id}', 'CirculationController@book_return');
				Route::post('circulations/search', 'CirculationController@search');
				Route::get('circulations/list/{member_id}', 'CirculationController@index');
				Route::resource('circulations','CirculationController');
			});

			Route::get('notifications/create/{id}', 'NotificationController@create');
			Route::resource('notifications','NotificationController');

			Route::get('book_requests', 'BookRequestController@index');
			Route::get('book_requests/{id}', 'BookRequestController@details')->name('book_requests.show');
			Route::get('book_requests/status/{id}/{status?}', 'BookRequestController@status');
		});

		//only for members
		Route::group(['middleware' => ['permission:Member']], function () {
			Route::get('books', 'BookController@index');
			Route::get('books/{id}', 'BookController@details');

			Route::get('my_circulations', 'CirculationController@my_circulations');
			Route::get('my_circulations/{id}', 'CirculationController@details')->name('my_circulations.show');

			Route::resource('my_book_requests','BookRequestController');
			Route::get('my_book_requests', 'BookRequestController@my_book_requests');

			Route::get('my_notifications', 'NotificationController@my_notifications');
			Route::get('my_notifications/{id}', 'NotificationController@details');
		});
	});
});

//cronjon url
Route::any('automatic_notify', 'NotificationController@automatic_notify');

//installation
Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

resources/views/backend/my_book_requests/modal/create.blade.php
<form action="{{route('my_book_requests.store')}}" class="form-horizontal form-groups-bordered ajax-submit" enctype="multipart/form-data" method="post" accept-charset="utf-8">
	@csrf
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Book Title</label>
			<input type="text" name="book_title" class="form-control" value="{{ old('book_title') }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Author Name</label>
			<input type="text" name="author_name" class="form-control" value="{{ old('author_name') }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Edition</label>
			<input type="text" name="edition" class="form-control" value="{{ old('edition') }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Year</label>
			<input type="text" name="year" class="form-control yearpicker" value="{{ old('year') }}" readonly required>
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group">
			<label class="form-control-label">Note</label>
			<textarea class="form-control" name="note">{{ old('note') }}</textarea>
		</div>
	</div>
	<div class="col-md-12 text-right">
		<button type="submit" class="btn btn-success">Save</button>
	</div>
</form>

resources/views/backend/my_book_requests/modal/edit.blade.php
<form action="{{ route('my_book_requests.update',$book_request->id) }}" class="form-horizontal form-groups-bordered ajax-submit" enctype="multipart/form-data" method="post" accept-charset="utf-8">
	@csrf
	@method('PUT')
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Book Title</label>
			<input type="text" name="book_title" class="form-control" value="{{ $book_request->book_title }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Author Name</label>
			<input type="text" name="author_name" class="form-control" value="{{ $book_request->author_name }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Edition</label>
			<input type="text" name="edition" class="form-control" value="{{ $book_request->edition }}" required>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<label class="form-control-label">Year</label>
			<input type="text" name="year" class="form-control yearpicker" value="{{ $book_request->year }}" readonly required>
		</div>
	</div>
	<div class="col-md-12">
		<div class="form-group">
			<label class="form-control-label">Note</label>
			<textarea class="form-control" name="note">{{ $book_request->note }}</textarea>
		</div>
	</div>
	<div class="col-md-12 text-right">
		<button type="submit" class="btn btn-success">Update</button>
	</div>
</form>

resources/views/backend/my_book_requests/modal/show.blade.php
<div class="table-responsive">
	<table class="table table-bordered table-view">
		<tr>
			<th>Book Title</th>
			<td>{{ $book_request->book_title }}</td>
		</tr>
		<tr>
			<th>Author Name</th>
			<td>{{ $book_request->author_name }}</td>
		</tr>
		<tr>
			<th>Edition</th>
			<td>{{ $book_request->edition }}</td>
		</tr>
		<tr>
			<th>Year</th>
			<td>{{ $book_request->year }}</td>
		</tr>
		<tr>
			<th>Requested</th>
			<td>{{ date_format($book_request->created_at,"Y-m-d") }}</td>
		</tr>
		<tr>
			<th>Note</th>
			<td>{{ $book_request->note }}</td>
		</tr>
		<tr>
			<th>Status</th>
			<td>
				@if($book_request->status == 0)
				<span class="badge badge-warning">Pending</span>
				@elseif($book_request->status == 1)
				<span class="badge badge-success">Accepted</span>
				@elseif($book_request->status ==2)
				<span class="badge badge-danger">Rejected</span>
				@endif
			</td>
		</tr>
	</table>
</div>