routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::group(['middleware' => ['install']], function () {

	Route::get('/', function () {
		return redirect('/dashboard');
	});

	Auth::routes();

	Route::group(['middleware' => ['auth']], function () {

		Route::any('/dashboard', 'DashboardController@index');

		Route::get('profile/show', 'ProfileController@profile_show');
		Route::get('profile/edit', 'ProfileController@profile_edit');
		Route::post('profile/update', 'ProfileController@profile_update');
		Route::get('password/change', 'ProfileController@password_change');
		Route::any('password/update', 'ProfileController@password_update');

		//only for Admin
		Route::group(['middleware' => ['permission:Admin,Librarian']], function () {
			Route::resource('users','UserController');

			Route::any('/general_settings', 'SettingsController@general_settings');

			Route::any('/notification_settings', 'SettingsController@notification_settings');

			Route::any('/backup_database', 'BackupController@backup_database');
		});

		//only for Admin,Librarian
		Route::group(['middleware' => ['permission:Admin,Librarian']], function () {
			Route::get('library/{page?}', 'LibraryController@index');

			Route::group(['prefix' => 'library'], function () {
				Route::resource('book_categories','BookCategoryController');

				Route::resource('books','BookController');

				Route::get('members/library_card/{id}', 'MemberController@library_card')->name('members.library_card');
				Route::resource('members','MemberController');

				Route::get('circulations/book_return_info/{id}', 'CirculationController@book_return_info');
				Route::post('circulations/book_return/{id}', 'CirculationController@book_return');
				Route::post('circulations/search', 'CirculationController@search');
				Route::get('circulations/list/{member_id}', 'CirculationController@index');
				Route::resource('circulations','CirculationController');
			});

			Route::get('notifications/create/{id}', 'NotificationController@create');
			Route::resource('notifications','NotificationController');

			Route::get('book_requests', 'BookRequestController@index');
			Route::get('book_requests/{id}', 'BookRequestController@details')->name('book_requests.show');
			Route::get('book_requests/status/{id}/{status?}', 'BookRequestController@status');
		});

		//only for members
		Route::group(['middleware' => ['permission:Member']], function () {
			Route::get('books', 'BookController@index');
			Route::get('books/{id}', 'BookController@details');

			Route::get('my_circulations', 'CirculationController@my_circulations');
			Route::get('my_circulations/{id}', 'CirculationController@details')->name('my_circulations.show');

			Route::resource('my_book_requests','BookRequestController');
			Route::get('my_book_requests', 'BookRequestController@my_book_requests');

			Route::get('my_notifications', 'NotificationController@my_notifications');
			Route::get('my_notifications/{id}', 'NotificationController@details');
		});
	});
});

//cronjon url
Route::any('automatic_notify', 'NotificationController@automatic_notify');

//installation
Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

app/Circulation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Circulation extends Model
{
    public function member() 
	{
		return $this->belongsTo('App\Member');
	}

	public function book() 
	{
		return $this->belongsTo('App\Book');
	}
}

app/Http/Controllers/CirculationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Circulation;

class CirculationController extends Controller
{
    /**
     * Instantiate a new PostController instance.
     *
     * @return void
     */
    public function __construct()
    {
        // Timezone
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        return redirect('library/circulations/list/' . $request->member_id);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($member_id)
    {   
        $member = \App\Member::where('member_id', $member_id)->first();
        $circulations = Circulation::where('member_id', $member->id)->orderBy('id', 'DESC')->get();
        return view('backend.library.circulations.index', compact('member_id','member', 'circulations'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function my_circulations()
    {
        $circulations = Circulation::where('member_id', get_member_id())->orderBy('id', 'DESC')->get();
        return view('backend.my_circulations.index', compact('circulations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if( ! $request->ajax()){
           return view('backend.library.circulations.create');
        }else{
           return view('backend.library.circulations.modal.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'member_id' => 'required',
            'book_id' => 'required',
            'issue_date' => 'required|date',
            'due_date' => 'required|date',
        ]);
        
        if ($validator->fails()) {
            if($request->ajax()){ 
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return back()->withErrors($validator)->withInput();
            }           
        }

        $book_issue = new Circulation();
        $book_issue->member_id = $request->member_id;
        $book_issue->book_id = $request->book_id;
        $book_issue->issue_date = $request->issue_date;
        $book_issue->due_date = $request->due_date;
        $book_issue->note = $request->note;
        $book_issue->save();

        if(! $request->ajax()){
           return back()->with('success', 'Information has been added');
        }else{
           return response()->json(['result'=>'success','message'=> 'Information has been added', 'redirect' => url('library/circulations/')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $circulation = Circulation::find($id);
        if( ! $request->ajax()){
           return view('backend.library.circulations.show', compact('circulation'));
        }else{
           return view('backend.library.circulations.modal.show', compact('circulation'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function details(Request $request, $id)
    {
        $circulation = Circulation::find($id);
        if( ! $request->ajax()){
           return view('backend.my_circulations.show', compact('circulation'));
        }else{
           return view('backend.my_circulations.modal.show', compact('circulation'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $book_issue = Circulation::find($id);
        if( ! $request->ajax()){
           return view('backend.library.circulations.edit', compact('book_issue'));
        }else{
           return view('backend.library.circulations.modal.edit', compact('book_issue'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'member_id' => 'required',
            'book_id' => 'required',
            'issue_date' => 'required|date',
            'due_date' => 'required|date',
        ]);
        
        if ($validator->fails()) {
            if($request->ajax()){ 
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return back()->withErrors($validator)->withInput();
            }           
        }

        $book_issue = Circulation::find($id);
        $book_issue->member_id = $request->member_id;
        $book_issue->book_id = $request->book_id;
        $book_issue->issue_date = $request->issue_date;
        $book_issue->due_date = $request->due_date;
        $book_issue->note = $request->note;
        $book_issue->save();

        if(! $request->ajax()){
           return redirect('library/circulations')->with('success', 'Information has been updated');
        }else{
           return response()->json(['result'=>'success','message'=> 'Information has been updated', 'redirect' => url()->previous()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function book_return_info(Request $request, $id)
    {
        $book_issue = Circulation::find($id);
        if( ! $request->ajax()){
           return view('backend.library.circulations.return', compact('book_issue'));
        }else{
           return view('backend.library.circulations.modal.return', compact('book_issue'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function book_return(Request $request, $id)
    {
        $validator = \Validator::make($request->all(), [
            'return_date' => 'required|date',
        ]);
        
        if ($validator->fails()) {
            if($request->ajax()){ 
                return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
            }else{
                return back()->withErrors($validator)->withInput();
            }           
        }

        $book_issue = Circulation::find($id);
        $book_issue->return_date = $request->return_date;
        $book_issue->is_return = 1;
        $book_issue->save();

        if(! $request->ajax()){
           return redirect('library/circulations')->with('success', 'Information has been updated');
        }else{
           return response()->json(['result'=>'success','message'=> 'Information has been updated', 'redirect' => url()->previous()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book_issue = Circulation::find($id);
        $book_issue->delete();

        return back()->with('success', 'Information has been deleted');
    }
}

app/Http/Controllers/LibraryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LibraryController extends Controller
{
    
    /**
     * Instantiate a new PostController instance.
     *
     * @return void
     */
    public function __construct()
    {
        // Timezone
        config(['app.timezone' => app_data('timezone')]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $book_categories = \App\BookCategory::orderBy('id', 'DESC')->get();
        $books = \App\Book::orderBy('id', 'DESC')->get();
        $members = \App\Member::orderBy('id', 'DESC')->get();
        $circulations = \App\Circulation::orderBy('id', 'DESC')->get();
        
        return view('backend.library.index',compact('book_categories', 'books', 'members', 'circulations'));
    }
}

resources/views/backend/library/circulations/create.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="card">
			<div class="card-header with-border">
				<strong class="card-title float-left">Add Issue</strong>
				<a href="{{ route('circulations.index') }}" style="color: #000;" class="float-right">
					<i class="fas fa-reply"></i>
				</a>
			</div>
			<div class="card-body">
				<form action="{{route('circulations.store')}}" class="form-horizontal form-groups-bordered validate" enctype="multipart/form-data" method="post" accept-charset="utf-8">
					@csrf
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Member Id</label>
							<select class="form-control select2" name="member_id" required>
								{{ create_member_option('id') }}
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Book Id</label>
							<select class="form-control select2" name="book_id" required>
								{{ create_option('books', 'id', 'book_id', old('book_id')) }}
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Issue Date</label>
							<input type="text" name="issue_date" class="form-control datepicker" value="{{ (old('issue_date') != '') ? old('issue_date') : \Carbon\Carbon::now()->toDateString() }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Due Date</label>
							<input type="text" name="due_date" class="form-control datepicker" value="{{ old('due_date') }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Note</label>
							<textarea class="form-control" name="note" >{{ old('note') }}</textarea>
						</div>
					</div>
					<div class="col-md-12 text-right">
						<button type="submit" class="btn btn-success">Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div> 
@endsection
@section('js-script')
<script type="text/javascript">
	$('select[name=member_id]').val('{{ old('member_id') }}');
	$('select[name=book_id]').val('{{ old('book_id') }}');
</script>
@stop

resources/views/backend/library/circulations/edit.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="card">
			<div class="card-header with-border">
				<strong class="card-title float-left">Edit</strong>
				<a href="{{ route('circulations.index') }}" style="color: #000;" class="float-right">
					<i class="fas fa-reply"></i>
				</a>
			</div>
			<div class="card-body">
				<form action="{{route('circulations.update',$book_issue->id)}}" class="form-horizontal form-groups-bordered validate" enctype="multipart/form-data" method="post" accept-charset="utf-8">
					@csrf
					@method('PUT')
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Member Id</label>
							<select class="form-control select2" name="member_id" required>
								{{ create_member_option('id') }}
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Book Id</label>
							<select class="form-control select2" name="book_id" required>
								{{ create_option('books', 'id', 'book_id', $book_issue->book_id) }}
							</select>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Issue Date</label>
							<input type="text" name="issue_date" class="form-control datepicker" value="{{ $book_issue->issue_date }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Due Date</label>
							<input type="text" name="due_date" class="form-control datepicker" value="{{ $book_issue->due_date }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Note</label>
							<textarea class="form-control" name="note" >{{ $book_issue->note }}</textarea>
						</div>
					</div>
					<div class="col-md-12 text-right">
						<button type="submit" class="btn btn-success">Update</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div> 
@endsection
@section('js-script')
<script type="text/javascript">
	$('select[name=member_id]').val('{{ $book_issue->member_id }}');
	$('select[name=book_id]').val('{{ $book_issue->book_id }}');
</script>
@stop

resources/views/backend/library/circulations/index.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
			<div class="card-header">
				<strong class="card-title float-left">Circulations</strong>
				<a href="{{ url('library/circulations') }}" class="btn btn-primary btn-sm float-right">
					<i class="fa fa-reply"></i>
				</a>
			</div>
			<div class="card-body">
				<form class="params-panel" action="{{ url('library/circulations/search') }}" method="post">
					@csrf
					<div class="col-md-6 offset-md-2">
						<div class="form-group">
							<select class="form-control select2" name="member_id">
								{{ create_member_option('member_id') }}
							</select>
						</div>
					</div>
					<div class="col-md-2 text-right">
						<button type="submit" class="btn btn-success btn-block">Search</button>
					</div>
				</form>
			</div>
			<div class="text-center">
				<h4>Circulations Of</h4>
				<h4>Member Id - {{ $member->member_id }}</h4>
				<h4>Member Name - {{ $member->user->name }}</h4>
			</div>
			<div class="card-body">
				<table class="table table-striped table-bordered data-table" style="width:100%">
					<thead>
						<tr>	
							<th>Book ID</th>
							<th>Issue date</th>
							<th>Due Date</th>
							<th>Return Date</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@php $i = 1; @endphp
						@foreach ($circulations as $data)
						<tr>
							<td>{{ $data->book->book_id }}</td>
							<td>{{ $data->issue_date }}</td>
							<td>{{ $data->due_date }}</td>
							<td>{{ $data->return_date }}</td>
							<td>
								@if($data->is_return == 1)
								<span class="badge badge-primary">Return</span>
								@elseif($data->is_return ==0)
								<span class="badge badge-danger">Not Return</span>
								@endif
							</td>
							<td class="text-center">
								<form action="{{ route('circulations.destroy',$data->id) }}" method="post">
									<a href="{{ route('circulations.show',$data->id) }}" class="btn btn-success btn-custom ajax-modal" data-title="Details"><i class="fas fa-eye" style="color: #fff" aria-hidden="true"></i></a>
									<a href="{{ route('circulations.edit',$data->id) }}" class="btn btn-warning btn-custom ajax-modal" data-title="Edit"><i class="fas fa-pencil-alt" style="color: #fff" aria-hidden="true"></i></a>
									@if($data->is_return == 0)
									<a href="{{ url('library/circulations/book_return_info/' . $data->id) }}" class="btn btn-primary btn-custom ajax-modal" data-title="Book Return Information"><i class="fas fa-reply" style="color: #fff" aria-hidden="true"></i></a>
									@endif
									<hr>
									<a href="{{ route('notifications.create', $data->id) }}" class="btn btn-info btn-custom ajax-modal" data-title="Edit"><i class="fas fa-envelope" style="color: #fff" aria-hidden="true"></i></a>
									@method('DELETE')
									@csrf
									<button type="submit" class="btn btn-danger btn-custom btn-remove"><i class="fas fa-eraser" aria-hidden="true"></i></button>
								</form>
							</td>
						</tr>
						@php $i++; @endphp
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@section('js-script')
<script type="text/javascript">
	$('select[name=member_id]').val('{{ $member_id }}');
</script>
@stop

resources/views/backend/library/circulations/return.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-md-6">
		<div class="card">
			<div class="card-header with-border">
				<strong class="card-title float-left">Book Return Information</strong>
				<a href="{{ route('circulations.index') }}" style="color: #000;" class="float-right">
					<i class="fas fa-reply"></i>
				</a>
			</div>
			<div class="card-body">
				<form action="{{ url('library/circulations/book_return/' . $book_issue->id) }}" class="form-horizontal form-groups-bordered" enctype="multipart/form-data" method="post" accept-charset="utf-8">
					@csrf
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Member Id</label>
							<input type="text" name="member_id" class="form-control datepicker" value="{{ $book_issue->member->member_id }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Book Id</label>
							<input type="text" name="book_id" class="form-control datepicker" value="{{ $book_issue->book->book_id }}" readonly required>
						</div>
					</div>
					<div class="col-md-12">
						<div class="form-group">
							<label class="form-control-label">Return Date</label>
							<input type="text" name="return_date" class="form-control datepicker" value="{{ (old('return_date') != '') ? old('return_date') : \Carbon\Carbon::now()->toDateString() }}" readonly required>
						</div>
					</div>
					<div class="col-md-12 text-right">
						<button type="submit" class="btn btn-success">Return</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div> 
@endsection

resources/views/backend/library/circulations/show.blade.php
@extends('layouts.backend')
@section('content')
<div class="row">
	<div class="col-lg-8">
		<div class="card">
			<div class="card-header">
				<h4>Details</h4>
			</div>
			<div class="card-body">
				<div class="default-tab tabs-left">
					<nav>
						<div class="nav nav-tabs nav-justified" id="nav-tab" role="tablist">
							<a class="nav-item nav-link active show" id="nav-home-tab" data-toggle="tab" href="#circulation" role="tab" aria-controls="nav-home" aria-selected="true">Circulation</a>
							<a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#member" role="tab" aria-controls="nav-contact" aria-selected="false">Member</a>
							<a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#book" role="tab" aria-controls="nav-profile" aria-selected="false">Book</a>
						</div>
					</nav>
					<div class="tab-content pt-2" id="nav-tabContent">
						<div class="tab-pane fade active show" id="circulation" role="tabpanel">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-bordered table-view">
											<tr>
												<th>Issue Date</th>
												<td>{{ $circulation->issue_date }}</td>
											</tr>
											<tr>
												<th>Due Date</th>
												<td>{{ $circulation->due_date }}</td>
											</tr>
											<tr>
												<th>Status</th>
												<td>
													@if($circulation->is_return == 1)
													<span class="badge badge-primary">Return</span>
													@elseif($circulation->is_return ==0)
													<span class="badge badge-danger">Not Return</span>
													@endif
												</td>
											</tr>
											@if($circulation->is_return == 1)
											<tr>
												<th>Return Date</th>
												<td>{{ $circulation->return_date }}</td>
											</tr>
											@endif
											<tr>
												<th>Note</th>
												<td>{{ $circulation->note }}</td>
											</tr>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="member" role="tabpanel">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-bordered table-view">
											<tr>
												<td colspan="2"><img src="{{  asset('public/uploads/images/' . $circulation->member->user->image) }}"></td>
											</tr>
											<tr>
												<th>Name</th>
												<td>{{ $circulation->member->user->name }}</td>
											</tr>
											<tr>
												<th>Phone</th>
												<td>{{ $circulation->member->user->phone }}</td>
											</tr>
											<tr>
												<th>Email</th>
												<td>{{ $circulation->member->user->email }}</td>
											</tr>
											<tr>
												<th>Member Type</th>
												<td>{{ $circulation->member->member_type }}</td>
											</tr>
											<tr>
												<th>Address</th>
												<td>{{ $circulation->member->address }}</td>
											</tr>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="book" role="tabpanel">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="table table-bordered table-view">
											<tr>
												<td colspan="4" class="text-center"><img src="{{  asset('public/uploads/images/' . $circulation->book->photo) }}"></td>
											</tr>
											<tr>
												<th>ISBN</th>
												<td>{{ $circulation->book->isbn }}</td>
												<th>Book Id</th>
												<td>{{ $circulation->book->book_id }}</td>
											</tr>
											<tr>
												<th>Title</th>
												<td>{{ $circulation->book->title }}</td>
												<th>Sub Title</th>
												<td>{{ $circulation->book->sub_title }}</td>
											</tr>
											<tr>
												<th>Author</th>
												<td>{{ $circulation->book->author }}</td>
												<th>Edition</th>
												<td>{{ $circulation->book->edition }}</td>
											</tr>
											<tr>
												<th>Edition Year</th>
												<td>{{ $circulation->book->edition_year }}</td>
												<th>Quantity</th>
												<td>{{ $circulation->book->quantity }}</td>
											</tr>
											<tr>
												<th>Publisher</th>
												<td>{{ $circulation->book->publisher }}</td>
												<th>Series</th>
												<td>{{ $circulation->book->series }}</td>
											</tr>
											<tr>
												<th>Category</th>
												<td>{{ $circulation->book->category->category_name }}</td>
												<th>Editor</th>
												<td>{{ $circulation->book->editor }}</td>
											</tr>
											<tr>
												<th>Publication Year</th>
												<td>{{ $circulation->book->publication_year }}</td>
												<th>Publication Place</th>
												<td>{{ $circulation->book->publication_place }}</td>
											</tr>
											@if($circulation->book->description == '')
											<tr>
												<th>Barcode</th>
												<td>{{ $circulation->book->barcode }}</td>
												<th>Description</th>
												<td>{{ $circulation->book->description }}</td>
											</tr>
											@else
											<tr>
												<th colspan="2">Barcode</th>
												<td colspan="2">{{ $circulation->book->barcode }}</td>
											</tr>
											<tr>
												<th colspan="2">Description</th>
												<td colspan="2">{{ $circulation->book->description }}</td>
											</tr>
											@endif
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection